services:
  mongodb:
    image: mongo:7
    container_name: mongodb-container
    hostname: mongodb
    networks:
      - graylog-network
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
    restart: on-failure

  datanode1:
    image: graylog/graylog-datanode:6.1.4
    container_name: datanode-container1
    hostname: datanode1
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: /var/lib/graylog-datanode/node-id
      GRAYLOG_DATANODE_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_DATANODE_MONGODB_URI: mongodb://mongodb:27017/graylog
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - graylog-network
    ports:
      - 8999:8999/tcp   # DataNode API
    volumes:
      - graylog-datanode1:/var/lib/graylog-datanode
    restart: on-failure

  datanode2:
    image: graylog/graylog-datanode:6.1.4
    container_name: datanode-container2
    hostname: datanode2
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: /var/lib/graylog-datanode/node-id
      GRAYLOG_DATANODE_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_DATANODE_MONGODB_URI: mongodb://mongodb:27017/graylog
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - graylog-network
    ports:
      - 8998:8998/tcp   # DataNode API
    volumes:
      - graylog-datanode2:/var/lib/graylog-datanode
    restart: on-failure

  datanode3:
    image: graylog/graylog-datanode:6.1.4
    container_name: datanode-container3
    hostname: datanode3
    environment:
      GRAYLOG_DATANODE_NODE_ID_FILE: /var/lib/graylog-datanode/node-id
      GRAYLOG_DATANODE_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_DATANODE_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_DATANODE_MONGODB_URI: mongodb://mongodb:27017/graylog
    ulimits:
      memlock:
        hard: -1
        soft: -1
      nofile:
        soft: 65536
        hard: 65536
    networks:
      - graylog-network
    ports:
      - 8997:8997/tcp   # DataNode API
    volumes:
      - graylog-datanode3:/var/lib/graylog-datanode
    restart: on-failure

  graylog:
    image: graylog/graylog:6.1.4
    container_name: graylog-container
    hostname: graylog
    depends_on:
      mongodb:
        condition: service_started
    entrypoint: /usr/bin/tini --  /docker-entrypoint.sh
    environment:
      GRAYLOG_NODE_ID_FILE: /usr/share/graylog/data/data/node-id
      GRAYLOG_PASSWORD_SECRET: ${GRAYLOG_PASSWORD_SECRET}
      GRAYLOG_ROOT_PASSWORD_SHA2: ${GRAYLOG_ROOT_PASSWORD_SHA2}
      GRAYLOG_HTTP_BIND_ADDRESS: 0.0.0.0:9000
      GRAYLOG_HTTP_EXTERNAL_URI: http://localhost:9000/
      GRAYLOG_MONGODB_URI: mongodb://mongodb:27017/graylog
    networks:
      - graylog-network
    ports:
    - 5044:5044/tcp   # Beats
    - 5140:5140/udp   # Syslog
    - 5140:5140/tcp   # Syslog
    - 5555:5555/tcp   # RAW TCP
    - 5555:5555/udp   # RAW UDP
    - 9000:9000/tcp   # Server API
    - 12201:12201/tcp # GELF TCP
    - 12201:12201/udp # GELF UDP
    #- 10000:10000/tcp # Custom TCP port
    #- 10000:10000/udp # Custom UDP port
    - 13301:13301/tcp # Forwarder data
    - 13302:13302/tcp # Forwarder config
    volumes:
      - graylog_data:/usr/share/graylog/data
      - graylog_journal:/usr/share/graylog/data/journal
    restart: on-failure

volumes:
  mongodb_data:
    driver: local
  mongodb_config:
    driver: local
  graylog-datanode1:
    driver: local
  graylog-datanode2:
    driver: local
  graylog-datanode3:
    driver: local
  graylog_data:
    driver: local
  graylog_journal:
    driver: local

networks:
  graylog-network:
    driver: bridge
